apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue
spec:
  selector:
    matchLabels:
      app: blue
  replicas: 1
  template:
    metadata:
      labels:
        app: blue
    spec:
      containers:
      - name: blue
        image: karthequian/helloworld:latest
        ports:
        - containerPort: 80
