apiVersion: apps/v1
kind: Deployment
metadata:
  name: soaktest
spec:
  replicas: 5
  selector:
    matchLabels:
      app: soaktest
  template:
    metadata:
      labels:
        app: soaktest
    spec:
      containers:
      - name: soaktest
        image: nickchase/soaktest
        ports:
        - containerPort: 80
